### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data\\Clean\\Image\\LIDC-IDRI-0100\\LIDC-IDRI-0100\\0100_CN001_slice000.npy'

### ISSUE THREAD

**Issue by oqlaalrefai** [jaeho3690/LIDC-IDRI-preprocessing#10]

**Comment by oqlaalrefai** [comment]
Can you help me?

**Comment by Dhruv-Singhh** [comment]
did you find any solution for this?

**Comment by Narratorx** [comment]
This worked for me:



else:
                print("Clean Dataset",pid)
                patient_clean_dir_image = CLEAN_DIR_IMAGE
                patient_clean_dir_mask = CLEAN_DIR_MASK
                # Path(patient_clean_dir_image).mkdir(parents=True, exist_ok=True)
                # Path(patient_clean_dir_mask).mkdir(parents=True, exist_ok=True)
            
                #There are patients that don't have nodule at all. Meaning, its a clean dataset. We need to use this for validation
                for slice in range(vol.shape[2]):
                    if slice >50:
                        break
                    lung_segmented_np_array = segment_lung(vol[:,:,slice])
                    lung_segmented_np_array[lung_segmented_np_array==-0] =0
                    lung_mask = np.zeros_like(lung_segmented_np_array)
                    #CN= CleanNodule, CM = CleanMask
                    # nodule_name = "{}/{}_CN001_slice{}".format(pid,pid[-4:],prefix[slice])
                    # mask_name = "{}/{}_CM001_slice{}".format(pid,pid[-4:],prefix[slice])
                    nodule_name = pid[-4:] + '_CN001_slice' + prefix[slice]
                    mask_name = pid[-4:] + '_CM001_slice' + prefix[slice]
                    meta_list = [pid[-4:],slice,prefix[slice],nodule_name,mask_name,0,False,True]

                    self.save_meta(meta_list)
                    np.save(str(patient_clean_dir_image) + '/' + nodule_name, lung_segmented_np_array)
                    np.save(str(patient_clean_dir_mask) + '/' + mask_name, lung_mask)

**Comment by Narratorx** [comment]
This worked for me:

else:
    print("Clean Dataset",pid)
    patient_clean_dir_image = CLEAN_DIR_IMAGE
    patient_clean_dir_mask = CLEAN_DIR_MASK
    # Path(patient_clean_dir_image).mkdir(parents=True, exist_ok=True)
    # Path(patient_clean_dir_mask).mkdir(parents=True, exist_ok=True)
            
    #There are patients that don't have nodule at all. Meaning, its a clean dataset. We need to use this for validation
     for slice in range(vol.shape[2]):
         if slice >50:
             break
         lung_segmented_np_array = segment_lung(vol[:,:,slice])
         lung_segmented_np_array[lung_segmented_np_array==-0] =0
         lung_mask = np.zeros_like(lung_segmented_np_array)
         # CN= CleanNodule, CM = CleanMask
         # nodule_name = "{}/{}_CN001_slice{}".format(pid,pid[-4:],prefix[slice])
         # mask_name = "{}/{}_CM001_slice{}".format(pid,pid[-4:],prefix[slice])
         nodule_name = pid[-4:] + '_CN001_slice' + prefix[slice]
         mask_name = pid[-4:] + '_CM001_slice' + prefix[slice]
          meta_list = [pid[-4:],slice,prefix[slice],nodule_name,mask_name,0,False,True]

          self.save_meta(meta_list)
           np.save(str(patient_clean_dir_image) + '/' + nodule_name, lung_segmented_np_array)
           np.save(str(patient_clean_dir_mask) + '/' + mask_name, lung_mask)

**Comment by Pollob001** [comment]
very good suggestion..its also  worked for me...Thanks
