### ISSUE TITLE
RuntimeError: Could not establish path to dicom files. Have you specified the `path` option in the configuration file C:\Users\rahul\pylidc.conf?

### ISSUE THREAD

**Issue by Dhruv-Singhh** [jaeho3690/LIDC-IDRI-preprocessing#14]
I am new to this pylidc can anyone help me with this. I think i have specifies the correct path but still i am getting this error.
specifying the path as
![image](https://user-images.githubusercontent.com/73129686/121372033-9db4a280-c95b-11eb-805a-0ee3cb21fa0a.png)

error
![image](https://user-images.githubusercontent.com/73129686/121371390-23841e00-c95b-11eb-98b5-27a30b9e798b.png)
![image](https://user-images.githubusercontent.com/73129686/121371457-30a10d00-c95b-11eb-98cb-23cdee4caa13.png)

contents of project folder.
![image](https://user-images.githubusercontent.com/73129686/121371799-7362e500-c95b-11eb-8b02-693e34448696.png)
![image](https://user-images.githubusercontent.com/73129686/121371878-7f4ea700-c95b-11eb-90f6-c3da1a2ccb7a.png)

**Comment by jaeho3690** [comment]
<img width="915" alt="스크린샷 2021-06-10 오전 6 08 00" src="https://user-images.githubusercontent.com/38973453/121429812-4857b000-c9b2-11eb-9581-a767f3af228f.png">


Did you set this?

**Comment by Dhruv-Singhh** [comment]
Thank you for the response and it is working now. I am still new to AI and sorry for asking this basic questions but it helps a lot when people like you come out of way to help. AI community is really good. Keep up the good work and thanks once again.

**Comment by jaeho3690** [comment]
Glad that I could be of help! Good luck!

**Comment by Pollob001** [comment]
OSError: Couldn't find DICOM files for Scan(id=12,patient_id=LIDC-IDRI-0001).

pylidc.conf is:
[dicom]
path =C:\Users\Pollob\ct img\LIDC-IDRI
warn = True

actually where is the problem? anyone please help me

**Comment by Nagi0** [comment]
I managed to make it work when I referenced the path where all the folders with DICOM files were located

C:\Users\username\NBIA_NODULES\manifest-1600709154662\LIDC-IDRI\
![image](https://github.com/jaeho3690/LIDC-IDRI-Preprocessing/assets/75706345/7a7df86d-977c-425b-8a41-e5175196144f)

**Comment by lixiangcog** [comment]
mark!

**Comment by Heroandzhang** [comment]
> OSError：找不到用于扫描的 DICOM 文件（id=12，patent_id=LIDC-IDRI-0001）。
> 
> pyldc.conf 是： [dicom] 路径 =C:\Users\Pollob\ct img\LIDC-IDRI warn = True
> 
> 其实问题出在哪里呢？有人请帮助我

replace \ to /
