### ISSUE TITLE
Issue in LIDC-IDRI-Segmentation

### ISSUE THREAD

**Issue by sarahchandran** [jaeho3690/LIDC-IDRI-preprocessing#17]
The issue that I am raising is regarding LIDC-IDRI-Segmentation project.
Since I was not able to receive a reply there, I am posting here and I apologize for posting query in some other project.

 I am unable to find the function crop_nodule in View_output.ipynb.
The function crop_nodule is called in function crop_patch.

**Comment by jaeho3690** [comment]
left a reply on the original repo!
