### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by aolakunleabayomi** [jaeho3690/LIDC-IDRI-preprocessing#2]
Good evening friend,

Trying to run the prepare_dataset code but not successful. I keep getting this error;

ImportError: cannot import name 'is_dir_path'

Please what can I  do

**Comment by aolakunleabayomi** [comment]
![15984698339411403534611121212358](https://user-images.githubusercontent.com/63426922/91347365-1a65fe00-e7da-11ea-925d-6f4ca6f6528e.jpg)

**Comment by jaeho3690** [comment]
Hello, if you have cloned the repository, there will be a "utils.py" script file. Inside the utils, there should be a function named "is_dir_path".  Make sure the function is there. The problem you are facing is a import error, not a code-wise problem
