### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by aolakunleabayomi** [jaeho3690/LIDC-IDRI-preprocessing#3]
Thanks for your response.

Utils.ipynb is there. I ran it. I found the function is_dir_path inside also but I keep getting 'cannot import name is_dir_path' error message.

Please do you have any other advice for me?

Thank you
![15987302683661984757525049354138](https://user-images.githubusercontent.com/63426922/91644910-7f1e9400-ea38-11ea-8b15-2437a016a5a8.jpg)

**Comment by jaeho3690** [comment]
Hi, I am not sure why the utils.py file is opened as a jupyter notebook. It should be a python script file

**Comment by jaeho3690** [comment]
Have you cloned the repository?

**Comment by aolakunleabayomi** [comment]
Thanks so much. I made the correction and it ran.
Just that I got a valueError when the program was about to load the data.
![15987543279342492559147407148936](https://user-images.githubusercontent.com/63426922/91649891-8bbede80-ea70-11ea-9846-5c06f9e28882.jpg)


Even though I properly downloaded the dataset. What do you suggest please?

**Comment by jaeho3690** [comment]
Sorry, I really have no idea, please check the library version of pylidc
