### ISSUE TITLE
RuntimeError: Could not establish path to dicom files. 

### ISSUE THREAD

**Issue by chinnujacob** [jaeho3690/LIDC-IDRI-preprocessing#4]
hi friend
I am a beginner in  python.I am new to pylidc. can u tel me how to  specifiy the `path` option in the configuration file C:\Users\varun\pylidc.conf?.
My LIDC data is available in folder D:\LIDCPREPROCESSING CODE\LIDC-IDRI-Preprocessing-master\LIDC-IDRI.
expecting  positive response
chinnu

**Comment by Dhruv-Singhh** [comment]
did you find the solution for this?

**Comment by Dhruv-Singhh** [comment]
i am also facing the same issue
