### ISSUE TITLE
cluster_annotations

### ISSUE THREAD

**Issue by macwolfz** [jaeho3690/LIDC-IDRI-preprocessing#5]
Hi, my name is David, I would like to thank you for taking the time to share your knowledge, it was really helpful for understanding such a complex topic.
A question, at the moment I try to run prepare_dataset I got this error message, I am a little bit lost, perhaps could you guide me with this?
  0%|                                                                                                                                                              | 0/135 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "prepare_dataset.py", line 173, in <module>
    test.prepare_dataset()
  File "prepare_dataset.py", line 99, in prepare_dataset
    nodules_annotation = scan.cluster_annotations()
AttributeError: 'NoneType' object has no attribute 'cluster_annotations'

**Comment by jaeho3690** [comment]
Hi David, glad to hear that you find my repository helpful. I am not sure but it seems to me that the pylidc library is not working. Did you install the configuration file for the pylidc library?

**Comment by macwolfz** [comment]
thank you for your answer, 
and yes, I made the file on "C:/Users/MYUSER/pylidc.conf'
this is the conf file:
[dicom]
path = C:/Users/sunbw/PycharmProjects/lung3d/LIDC-IDRI-Preprocessing/LIDC-IDRI/LIDC-IDRI-0001/
warn = True


also, when trying to install it directly, my environment caused some troubles so I installed everything with pip list:
absl-py                0.11.0
albumentations         0.4.5
argon2-cffi            20.1.0
astor                  0.8.1
async-generator        1.10
attrs                  20.2.0
backcall               0.2.0
bleach                 3.2.1
certifi                2020.6.20
cffi                   1.14.3
chardet                3.0.4
colorama               0.4.4
cycler                 0.10.0
decorator              4.4.2
defusedxml             0.6.0
dicom                  0.9.9.post1
efficientnet-pytorch   0.6.3
entrypoints            0.3
future                 0.18.2
gast                   0.4.0
grpcio                 1.31.0
h5py                   2.10.0
idna                   2.10
imageio                2.3.0
imgaug                 0.2.6
importlib-metadata     2.0.0
ipykernel              5.3.4
ipython                7.16.1
ipython-genutils       0.2.0
ipywidgets             7.5.1
jedi                   0.17.2
Jinja2                 2.11.2
joblib                 0.17.0
jsonschema             3.2.0
jupyter                1.0.0
jupyter-client         6.1.7
jupyter-console        6.2.0
jupyter-core           4.6.3
jupyterlab-pygments    0.1.2
kaggle                 1.5.9
Keras                  2.4.3
Keras-Applications     1.0.8
Keras-Preprocessing    1.1.0
kiwisolver             1.3.1
Markdown               3.3.2
MarkupSafe             1.1.1
matplotlib             3.3.2
MedPy                  0.4.0
mistune                0.8.4
mkl-fft                1.2.0
mkl-random             1.1.1
mkl-service            2.3.0
nbclient               0.5.1
nbconvert              6.0.7
nbformat               5.0.8
nest-asyncio           1.4.2
networkx               2.5
notebook               6.1.4
numpy                  1.18.4
opencv-python-headless 4.4.0.46
packaging              20.4
pandas                 1.1.4
pandocfilters          1.4.3
parso                  0.7.1
pickleshare            0.7.5
Pillow                 8.0.1
pip                    20.2.4
pip-autoremove         0.9.1
prometheus-client      0.8.0
prompt-toolkit         3.0.8
protobuf               3.13.0
pycparser              2.20
pydicom                2.1.0
Pygments               2.7.2
pylidc                 0.2.1
pyparsing              2.4.7
pyreadline             2.1
pyrsistent             0.17.3
python-dateutil        2.8.1
python-slugify         4.0.1
pytz                   2020.4
PyWavelets             1.1.1
pywin32                228
pywinpty               0.5.7
PyYAML                 5.3.1
pyzmq                  19.0.2
qtconsole              4.7.7
QtPy                   1.9.0
requests               2.24.0
scikit-image           0.17.2
scikit-learn           0.23.2
scipy                  1.4.1
Send2Trash             1.5.0
setuptools             50.3.0.post20201006
SimpleITK              2.0.1
six                    1.15.0
sklearn                0.0
slugify                0.0.1
SQLAlchemy             1.3.20
tensorboard            1.14.0
tensorflow             1.14.0
tensorflow-estimator   1.14.0
termcolor              1.1.0
terminado              0.9.1
testpath               0.4.4
text-unidecode         1.3
threadpoolctl          2.1.0
tifffile               2020.9.3
torch                  1.5.0
torchvision            0.6.0
tornado                6.1
tqdm                   4.42.1
traitlets              4.3.3
urllib3                1.25.11
wcwidth                0.2.5
webencodings           0.5.1
Werkzeug               1.0.1
wheel                  0.35.1
widgetsnbextension     3.5.1
wincertstore           0.2
wrapt                  1.12.1
zipp                   3.4.0

**Comment by macwolfz** [comment]
> Hi David, glad to hear that you find my repository helpful. I am not sure but it seems to me that the pylidc library is not working. Did you install the configuration file for the pylidc library?

thank you for your answer,
and yes, I made the file on "C:/Users/MYUSER/pylidc.conf'
this is the conf file:
[dicom]
path = C:/Users/sunbw/PycharmProjects/lung3d/LIDC-IDRI-Preprocessing/LIDC-IDRI/LIDC-IDRI-0001/
warn = True

also, when trying to install it directly, my environment caused some troubles so I installed everything with pip list:
absl-py 0.11.0
albumentations 0.4.5
argon2-cffi 20.1.0
astor 0.8.1
async-generator 1.10
attrs 20.2.0
backcall 0.2.0
bleach 3.2.1
certifi 2020.6.20
cffi 1.14.3
chardet 3.0.4
colorama 0.4.4
cycler 0.10.0
decorator 4.4.2
defusedxml 0.6.0
dicom 0.9.9.post1
efficientnet-pytorch 0.6.3
entrypoints 0.3
future 0.18.2
gast 0.4.0
grpcio 1.31.0
h5py 2.10.0
idna 2.10
imageio 2.3.0
imgaug 0.2.6
importlib-metadata 2.0.0
ipykernel 5.3.4
ipython 7.16.1
ipython-genutils 0.2.0
ipywidgets 7.5.1
jedi 0.17.2
Jinja2 2.11.2
joblib 0.17.0
jsonschema 3.2.0
jupyter 1.0.0
jupyter-client 6.1.7
jupyter-console 6.2.0
jupyter-core 4.6.3
jupyterlab-pygments 0.1.2
kaggle 1.5.9
Keras 2.4.3
Keras-Applications 1.0.8
Keras-Preprocessing 1.1.0
kiwisolver 1.3.1
Markdown 3.3.2
MarkupSafe 1.1.1
matplotlib 3.3.2
MedPy 0.4.0
mistune 0.8.4
mkl-fft 1.2.0
mkl-random 1.1.1
mkl-service 2.3.0
nbclient 0.5.1
nbconvert 6.0.7
nbformat 5.0.8
nest-asyncio 1.4.2
networkx 2.5
notebook 6.1.4
numpy 1.18.4
opencv-python-headless 4.4.0.46
packaging 20.4
pandas 1.1.4
pandocfilters 1.4.3
parso 0.7.1
pickleshare 0.7.5
Pillow 8.0.1
pip 20.2.4
pip-autoremove 0.9.1
prometheus-client 0.8.0
prompt-toolkit 3.0.8
protobuf 3.13.0
pycparser 2.20
pydicom 2.1.0
Pygments 2.7.2
pylidc 0.2.1
pyparsing 2.4.7
pyreadline 2.1
pyrsistent 0.17.3
python-dateutil 2.8.1
python-slugify 4.0.1
pytz 2020.4
PyWavelets 1.1.1
pywin32 228
pywinpty 0.5.7
PyYAML 5.3.1
pyzmq 19.0.2
qtconsole 4.7.7
QtPy 1.9.0
requests 2.24.0
scikit-image 0.17.2
scikit-learn 0.23.2
scipy 1.4.1
Send2Trash 1.5.0
setuptools 50.3.0.post20201006
SimpleITK 2.0.1
six 1.15.0
sklearn 0.0
slugify 0.0.1
SQLAlchemy 1.3.20
tensorboard 1.14.0
tensorflow 1.14.0
tensorflow-estimator 1.14.0
termcolor 1.1.0
terminado 0.9.1
testpath 0.4.4
text-unidecode 1.3
threadpoolctl 2.1.0
tifffile 2020.9.3
torch 1.5.0
torchvision 0.6.0
tornado 6.1
tqdm 4.42.1
traitlets 4.3.3
urllib3 1.25.11
wcwidth 0.2.5
webencodings 0.5.1
Werkzeug 1.0.1
wheel 0.35.1
widgetsnbextension 3.5.1
wincertstore 0.2
wrapt 1.12.1
zipp 3.4.0

**Comment by jaeho3690** [comment]
I think the conf file might be the problem.
Try
path = C:/Users/sunbw/PycharmProjects/lung3d/LIDC-IDRI-Preprocessing/LIDC-IDRI

**Comment by macwolfz** [comment]
thanks for the update, I did it but still getting the same error, I will try to set again the environment

**Comment by jaeho3690** [comment]
Best of luck!

**Comment by Jongchan** [comment]
@macwolfz In my case, I somehow changed the folder names, and thus the pylidc was not working.
Please make sure that the pid (or patient) in the following line is in the specified format (LIDC-IDRI-xxxx)
https://github.com/jaeho3690/LIDC-IDRI-Preprocessing/blob/fe5012cee158e8c8070dbaab6f24a1c157ab2bc4/prepare_dataset.py#L97

**Comment by silpacs001** [comment]
I had the same issue, removing the license file inside LIDC-IDRI folder will resolve this issue. Because before considering LIDC-IDRI-0001 it will take LISCENCE file.

**Comment by bachlebi11-035** [comment]
I had same problem, can you help me to fix that ?

**Comment by linkeaphla** [comment]
I change the version of pylidc: pylidc==0.2.1
It can run smoothly.I think maybe the function exits in the old version.


> I had same problem, can you help me to fix that ?
