### ISSUE TITLE
How many classes

### ISSUE THREAD

**Issue by harsharaman** [jaeho3690/LIDC-IDRI-preprocessing#7]
Hi Jaeho, this is rather a (stupid) question than an issue. What are the number of classes for segmentation from this dataset? 2, right? Malignant or not?

**Comment by jaeho3690** [comment]
Hi, I am not entirely sure by what you meant. For segmentation, the segmentation model should find any nodule. So I guess there would be 2 classes: one for non nodule and nodule. For classification, you have 2 classes as well. Non-cancer and cancerous. Remember, nodule doesn't necessarily mean cancer. hope this helps
